#########################################################################
#       PRESCRIPTION DESCRIPTION:
#   This prescription is used to perform metadynamics on Chignolin
#   
#   A simple equilibriation protocol is used to equilibrate the system:
#     1. ENERGY MINIMISATION
#        An energy minimisation is performed to relex the system into a local minimum
#     2. NVT PRE-EQUILIBRIATION
#        An NVT simulation is performed at 300 K, this is used to equilibrate the system's water molecules
#        This allows the pressure of the system to reach equilibrium
#        Position restraints are applied to the protein and ligand, as we are just equilibrating water
#     3. NPT PRE-EQUILIBRIATION
#        An NPT simulation is performed at 300 K, this is used to further equilibrate the system's water molecules
#        This allows the box size of the system to reach equilibrium
#        Position restraints are applied to the protein and ligand, as we are just equilibrating water
#     4. SLOW INTERGRATOR STEP
#        This step is run without any restraints, sometimes the removal of restraints can cause numerical errors
#        To prevent this, we run this step using a small timestep of 0.5 fs
#     5. EQUILIBRIATION
#        An unrestrained NPT simulation is performed for 5 nanoseconds
#        No measurements are taken during this simulation, we are just equilibrating the system
#        Before you run any analysis on the following PRODUCTION MD step, check the vitals report for this step
#        If this step has not reached equilibriation, it is best practace to extend the duration of this step 
#        before running your PRODUCTION MD step
#     6. PRODUCTION METADYNAMICS
#        Metadynamics is performed for 10 nanoseconds
#        Bias variables are constructed using distances of important hydrogen bonds
########################################################################
pathInfo:
  inputDir: /home/esp/scriptDevelopment/drMD/ExampleInputs/Worked_Example_6_Chignolin
  outputDir: /home/esp/scriptDevelopment/drMD/ExampleInputs/Worked_Example_6_Chignolin/outputs
  
########################################################################
hardwareInfo:
  parallelCPU: 1
  platform: CUDA
  subprocessCpus: 1
########################################################################
miscInfo:
  pH: 7.4
  firstAidMaxRetries: 10
  boxGeometry: cubic
  writeMyMethodsSection: True
  skipPdbTriage: False
  trajectorySelections:
    - selection:
        keyword: protein
    - selection:
        keyword: ligand
    - selection:
        keyword: water

########################################################################
equilibrationRestraints: &equilibrationRestraints
  - restraintType: position
    parameters:
      k: 1000
    selection:
      keyword: protein

  - restraintType: position
    selection: 
      keyword: ligand  
    parameters:
      k: 1000
########################################################################
simulationInfo:
  - stepName: 01_energy_minimisation
    simulationType: EM
    temperature: 300
    maxIterations: -1
########################################################################
  - stepName: 02_NVT_pre-equilibration
    simulationType: NVT
    duration: 100 ps
    timestep: 4 fs
    heavyProtons: True
    temperature: 300
    logInterval: 1 ps
    restraintInfo: *equilibrationRestraints

########################################################################
  - stepName: 03_NPT_pre-equilibration
    simulationType: NPT
    duration: 100 ps
    timestep: 4 fs
    heavyProtons: True
    temperature: 300
    logInterval: 1 ps
    restraintInfo: *equilibrationRestraints

########################################################################
  - stepName: 04_NpT_slowIntegrator
    simulationType: NpT
    duration: 10 ps
    timestep: 0.5 fs
    temperature: 300
    logInterval: 1 ps
########################################################################
  - stepName: 05_Equilibration
    simulationType: NpT
    duration: 5 ns
    timestep: 4 fs
    heavyProtons: True
    temperature: 300
    logInterval: 500 ps
########################################################################
  - stepName: 06_Metadynamics
    simulationType: META
    duration: 10 ns
    timestep: 2 fs
    heavyProtons: False
    temperature: 300
    logInterval: 10 ps
    metaDynamicsInfo:
      height: 0.8
      biasFactor: 10
      frequency: 500
      biases:
        - biasVar: distance
          minValue: 2.7
          maxValue: 10
          biasWidth: 0.5
          selection: 
            keyword: custom
            customSelection:
              - {CHAIN_ID: A, RES_NAME: ASP, RES_ID: 3, ATOM_NAME: O}
              - {CHAIN_ID: A, RES_NAME: GLY, RES_ID: 7, ATOM_NAME: N}
        - biasVar: distance
          minValue: 2.7
          maxValue: 10
          biasWidth: 0.5
          selection: 
            keyword: custom
            customSelection:
              - {CHAIN_ID: A, RES_NAME: ASP, RES_ID: 3, ATOM_NAME: N}
              - {CHAIN_ID: A, RES_NAME: THR, RES_ID: 8, ATOM_NAME: O}
################################################
aftercareInfo:
  clusterInfo:
    stepNames: [06_Metadynamics] 
    nClusters: 25
    clusterBy:
      - selection:
          keyword: protein
    removeAtoms:
      - selection:
          keyword: water
      - selection:
          keyword: ions
  collateVitalsReports: True