########################################################################
#   This is the world's worst config.
#   Do not use it!
#   If you use this as an input to drMD, you will see the configTriage error
#
#   World's worst config waits,
#   Never to be used again—
#   Errors in each line.
#
#
#
########################################################################
pathInfo:
  inputDir: /correctly/formatted/but/does/not/exist
  outputDir: NOTaDIR
########################################################################
hardwareInfo:
  platform: CUDA
  subprocessCpus: 1
  parallelCPU: 100

ligandInfo:
  - ligandName: FAD
    toppar: No
    mol2: yesplease
    charge: -2
  - ligandName: PLM
    toppar: True
    mol2: nothanks
    charge: -2
########################################################################
miscInfo:
  pH: 25
  firstAidMaxRetries: RATS
  boxGeometry: oblong
  writeMyMethodsSection: eggs
  skipPdbTriage: yesplease
  trajectorySelections:
  - selection:
      keyword: broken
  - selection:
      keyword: custom
      customSelection:
      - {RES_NAME: all, RES_ID:  sausages, ATOM_NAME: CA}
########################################################################
equilibriationRestraints: &equilibriationRestraints
    - restraintType: position
      parameters:
        k: 1000
      selection:
        keyword: protein

    - restraintType: position
      selection: 
        keyword: eggs  
      parameters:
        k: 1000

########################################################################
simulationInfo:
  - stepName: 01_energy_minimisation
    simulationType: EM
    maxIterations: 1000
########################################################################
  - stepName: 02_NVT_pre-equilibraition
    simulationType: NVT
    duration: 100
    timestep: 4
    heavyProtons: eggs
    temperature: 300
    logInterval: 10 ps
    restraintInfo: *equilibriationRestraints

# ########################################################################
  - stepName: 1
    simulationType: NPT
    duration: 100 ps
    timestep: 4 fs
    heavyProtons: True
    temperature: -20
    logInterval: 10 ps
    restraintInfo: None

################################################

postSimulationInfo:
  clusterInfo:
    stepNames: [NOTADIR] 
    nClusters: -1
    clusterBy:
    - selection:
        keyword: nothing
    removeAtoms:
      - selection:
      - selection:
          keyword: custom
          customSelection:
          - {RES_NAME: all, RES_ID:  rubbish, ATOM_NAME: CA}
  collateVitalsReports: True
  endPointInfo:
    stepNames: [01_energy_minimisation]
    removeAtoms: 
    - selection:
        keyword: ions
    - selection:
        keyword: water
  removeAllSimulationDirs: yesplease



